version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_NAME=your_db_name
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    build: .
    ports:
      - "4200:4200"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A smart_healthcare worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=smart_healthcare.settings
    user: nobody  # Or create a specific user for Celery

  celery-beat:
    build: ./backend
    command: celery -A smart_healthcare beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=smart_healthcare.settings
    user: nobody  # Or create a specific user for Celery Beat

volumes:
  postgres_data: