   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: backend
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: backend
     template:
       metadata:
         labels:
           app: backend
       spec:
         containers:
         - name: backend
           image: your-docker-username/backend:latest
           ports:
           - containerPort: 8000
           env:
           - name: DEBUG
             value: "0"
           - name: DJANGO_ALLOWED_HOSTS
             value: "*"  # Be more specific in production
           - name: DB_NAME
             value: your_db_name
           - name: DB_USER
             value: your_db_user
           - name: DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: DB_PASSWORD
           - name: DB_HOST
             value: postgres
           - name: DB_PORT
             value: "5432"
           - name: EMAIL_HOST_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: EMAIL_HOST_PASSWORD